# Generated by Django 5.2.6 on 2025-10-13 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.TextField()),
                ('education_required', models.CharField(max_length=100)),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('work_environment', models.TextField()),
                ('related_fields', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobMarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_year', models.IntegerField()),
                ('demand_level', models.CharField(max_length=50)),
                ('average_salary_trend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('top_locations', models.TextField()),
                ('key_skills_in_demand', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.career')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('education_level', models.CharField(choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'PhD')], max_length=3)),
                ('current_field', models.CharField(blank=True, max_length=100)),
                ('interests', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('personality_type', models.CharField(blank=True, max_length=4)),
                ('resume_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency_level', models.IntegerField()),
                ('years_experience', models.IntegerField(default=0)),
                ('assessed_date', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField()),
                ('question_2', models.IntegerField()),
                ('question_3', models.IntegerField()),
                ('question_4', models.IntegerField()),
                ('question_5', models.IntegerField()),
                ('question_6', models.IntegerField()),
                ('question_7', models.IntegerField()),
                ('question_8', models.IntegerField()),
                ('question_9', models.IntegerField()),
                ('question_10', models.IntegerField()),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reasoning', models.TextField()),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.career')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.userprofile')),
            ],
        ),
    ]
