# Generated by Django 5.2.6 on 2025-10-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your resume in PDF or DOCX format', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'PhD')], default='UG', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Extracted text content from resume file'),
        ),
    ]
