# Generated by Django 5.2.6 on 2025-10-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0002_userprofile_resume_file_userprofile_resume_filename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillassessment',
            old_name='assessed_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='skillassessment',
            name='proficiency_level',
        ),
        migrations.RemoveField(
            model_name='skillassessment',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='years_of_experience',
            field=models.FloatField(default=0),
        ),
    ]
