# Generated by Django 5.2.6 on 2025-12-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0003_rename_assessed_date_skillassessment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('course', 'Course'), ('article', 'Article'), ('book', 'Book')], max_length=20)),
                ('platform', models.CharField(max_length=100)),
                ('skill_tag', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='ai_recommender.career')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('career', 'step_number')},
            },
        ),
    ]
