# Generated by Django 5.2.6 on 2025-12-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0005_skill_learningresource_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Config key (e.g. MIN_MATCH_SCORE)', max_length=50, unique=True)),
                ('value', models.CharField(help_text='Config value', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='ai_weight',
            field=models.FloatField(default=1.0, help_text='Weightage for AI recommendation priority'),
        ),
        migrations.AddField(
            model_name='career',
            name='future_scope',
            field=models.TextField(blank=True, help_text='Details about future prospects'),
        ),
        migrations.AddField(
            model_name='career',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma-separated interests suitable for this career'),
        ),
        migrations.AddField(
            model_name='career',
            name='salary_range',
            field=models.CharField(blank=True, help_text='e.g. $50k - $80k', max_length=100),
        ),
    ]
