# Generated by Django 5.2.6 on 2025-12-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0006_aiconfig_career_ai_weight_career_future_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(default='AI Pattern Analysis', max_length=100)),
                ('skills_detected', models.TextField(help_text='Skills found that triggered this suggestion')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending AI Insight'), ('APPROVED', 'Approved (Added to Database)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
            ],
        ),
    ]
