# Generated by Django 5.2.6 on 2025-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0007_suggestedcareer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('domain', models.CharField(help_text='Matches Career Domain (e.g. Medical, Engineering)', max_length=100)),
                ('sub_domain', models.CharField(blank=True, max_length=100)),
                ('required_skills', models.TextField(help_text='Comma-separated skills')),
                ('education_required', models.CharField(blank=True, max_length=200)),
                ('industry_type', models.CharField(choices=[('PRIVATE', 'Private Sector'), ('GOVT', 'Government & PSU'), ('STARTUP', 'Startup & Innovation'), ('FREELANCE', 'Freelance & Gig Economy')], default='PRIVATE', max_length=20)),
                ('trend_reason', models.TextField(help_text='Why is this trending? (e.g. AI Boom, Policy Change)')),
                ('trend_score', models.IntegerField(default=50, help_text='1-100 Score for sorting priority')),
                ('source', models.CharField(default='Manual', help_text='Manual or AI-Suggested', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='domain',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
    ]
